version: 0.2

env:
  parameter-store:
    POSTMAN: /Postman/Key
    LISTS_COLLECTION_ID: /Postman/Collection/Lists
    NOTFOUND_COLLECTION_ID: /Postman/Collection/NotFound
    PRODUCTS_COLLECTION_ID: /Postman/Collection/Products
    CONTACT_COLLECTION_ID: /Postman/Collection/Contact

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - echo Lists Collection ID $LISTS_COLLECTION_ID
      - echo Environment ID $ENVIRONMENT_ID
      - echo Installing Newman
      - npm install -g newman@4.5.7
  build:
    commands:
      - newman run https://api.getpostman.com/collections/$LISTS_COLLECTION_ID?apikey=$POSTMAN --environment https://api.getpostman.com/environments/$ENVIRONMENT_ID?apikey=$POSTMAN
      - newman run https://api.getpostman.com/collections/$NOTFOUND_COLLECTION_ID?apikey=$POSTMAN --environment https://api.getpostman.com/environments/$ENVIRONMENT_ID?apikey=$POSTMAN
      - newman run https://api.getpostman.com/collections/$PRODUCTS_COLLECTION_ID?apikey=$POSTMAN --environment https://api.getpostman.com/environments/$ENVIRONMENT_ID?apikey=$POSTMAN
      - newman run https://api.getpostman.com/collections/$CONTACT_COLLECTION_ID?apikey=$POSTMAN --environment https://api.getpostman.com/environments/$ENVIRONMENT_ID?apikey=$POSTMAN
