version: 0.1

phases:
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install --user aws-sam-cli
      - /root/.local/bin/sam --version
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - /root/.local/bin/sam package --template-file Lists/template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file lists-packaged.yaml
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - lists-packaged.yaml
  discard-paths: yes
