version: 0.2

phases:
  pre_build:
    commands:
      - pip install -q --upgrade pip
      - pip install -Iv moto==1.3.14
      - pip install -q --user pytest boto3 requests_mock --no-warn-script-location
      - /root/.local/bin/pytest --version
  build:
    commands:
      - /root/.local/bin/pytest --disable-pytest-warnings Lists/tests/
      - /root/.local/bin/pytest --disable-pytest-warnings NotFound/tests/
      - /root/.local/bin/pytest --disable-pytest-warnings Products/tests/
      - /root/.local/bin/pytest --disable-pytest-warnings Contact/tests/
