# A collection of methods that are common across all modules.
import re
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)
if logger.handlers:
    handler = logger.handlers[0]
    handler.setFormatter(logging.Formatter("[%(levelname)s]\t%(asctime)s.%(msecs)dZ\t%(aws_request_id)s\t%(module)s:%(funcName)s\t%(message)s\n", "%Y-%m-%dT%H:%M:%S"))


def create_response(code, body):
    logger.info("Creating response with status code ({}) and body ({})".format(code, body))
    response = {'statusCode': code,
                'body': body,
                'headers': {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*'
                }}
    return response


def get_table_name(osenv):
    try:
        table_name = osenv['TABLE_NAME']
        logger.info("TABLE_NAME environment variable value: " + table_name)
    except KeyError:
        logger.error('TABLE_NAME environment variable not set correctly.')
        raise Exception('TABLE_NAME environment variable not set correctly.')

    return table_name


def get_identity(event, osenv):
    try:
        userArn = event['requestContext']['identity']['userArn']
        cognito_user_id = event['requestContext']['identity']['cognitoIdentityId']
        cognito_authentication_provider = event['requestContext']['identity']['cognitoAuthenticationProvider']
    except KeyError:
        logger.error("There was no identity context in API event.")
        raise Exception("There was no identity context in API event.")

    # Check to see if request was generated by postman, which doesn't authenticate via cognito.
    pattern = re.compile("^arn:aws:iam::[0-9]{12}:user/ApiTestUser$")
    pattern2 = re.compile("^arn:aws:iam::[0-9]{12}:user/ApiTestUser2$")
    if pattern.match(userArn):
        logger.info('Request was from postman, using API test identity.')
        identity = get_postman_identity(osenv, 1)
    elif pattern2.match(userArn):
        logger.info('Request was from postman, using API test identity.')
        identity = get_postman_identity(osenv, 2)
    else:
        if cognito_user_id is None:
            raise Exception("There was no cognitoIdentityId in the API event.")

        identity = cognito_authentication_provider.split(':')[-1]
        logger.info('cognitoIdentityId was retrieved from event.')

    return identity


def get_postman_identity(osenv, id):
    if id == 2:
        try:
            os_identity = osenv['POSTMAN_USERPOOL_SUB2']
        except KeyError:
            raise Exception('POSTMAN_USERPOOL_SUB2 environment variables not set correctly.')
    else:
        try:
            os_identity = osenv['POSTMAN_USERPOOL_SUB']
        except KeyError:
            raise Exception('POSTMAN_USERPOOL_SUB environment variables not set correctly.')

    return os_identity


def get_product_id(event):
    try:
        product_id = event['pathParameters']['id']
        logger.info("Product ID: " + product_id)
    except Exception:
        logger.error("API Event did not contain a Product ID in the path parameters.")
        raise Exception('API Event did not contain a Product ID in the path parameters.')

    return product_id
