import json
import os
import boto3
import logging
import time
import uuid
import re

logger = logging.getLogger()
logger.setLevel(logging.INFO)
if logger.handlers:
    handler = logger.handlers[0]
    handler.setFormatter(logging.Formatter("[%(levelname)s]\t%(asctime)s.%(msecs)dZ\t%(aws_request_id)s\t%(module)s:%(funcName)s\t%(message)s\n", "%Y-%m-%dT%H:%M:%S"))


dynamodb = boto3.client('dynamodb')


def handler(event, context):
    response = create_main(event)
    return response


def create_main(event):
    try:
        table_name = get_table_name()
        identity = get_identity(event)
        listId = generate_list_id(identity['cognitoIdentityId'], table_name)
        message = put_item_in_table(table_name, identity['cognitoIdentityId'], identity['userPoolSub'], listId)
    except Exception as e:
        logger.error("Exception: {}".format(e))
        response = create_response(500, json.dumps({'error': str(e)}))
        logger.info("Returning response: {}".format(response))
        return response

    data = {'listId': listId, 'message': message}

    response = create_response(200, json.dumps(data))
    return response


def generate_list_id(cognito_identity_id, table_name):
    # Generate a random uid, then check that the user does not already have a list with that ID.
    Invalid = True
    while Invalid:
        newlistId = uuid.uuid4().hex[:8]
        logger.info("Generated List ID: {}".format(newlistId))

        key = {
            'userId': {'S': cognito_identity_id},
            'listId': {'S': newlistId}
        }

        response = dynamodb.get_item(TableName=table_name, Key=key)

        if 'Item' in response:
            logger.info("Generated List ID existed: {}".format(response))
        else:
            logger.info("List ID ({}) unique in table for user: {}".format(newlistId, cognito_identity_id))
            Invalid = False

    return newlistId


def put_item_in_table(table_name, cognito_identity_id, user_pool_sub, listId):
    item = {
        'userId': {'S': cognito_identity_id},
        'userPoolSub': {'S': user_pool_sub},
        'listId': {'S': listId},
        'createdAt': {'N': str(int(time.time()))}
    }

    logger.info("Put item for lists table: {}".format(item))

    try:
        dynamodb.put_item(TableName=table_name, Item=item)
    except Exception as e:
        logger.error("List not could be created: {}".format(e))
        raise

    message = "List was created."

    return message


def get_identity(event):
    identity = {}

    try:
        userArn = event['requestContext']['identity']['userArn']
        cognito_identity_id = event['requestContext']['identity']['cognitoIdentityId']
        cognito_authentication_provider = event['requestContext']['identity']['cognitoAuthenticationProvider']
    except KeyError:
        logger.error("There was no identity context in API event.")
        raise Exception("There was no identity context in API event.")

    # Check to see if request was generated by postman, which doesn't authenticate via cognito.
    pattern = re.compile("^arn:aws:iam::[0-9]{12}:user/ApiTestUser")
    if pattern.match(userArn):
        api_identity = get_api_identity()
        identity["cognitoIdentityId"] = api_identity["API_IDENTITY_ID"]
        identity["userPoolSub"] = api_identity["API_USERPOOL_SUB"]
    else:
        if cognito_identity_id is None:
            raise Exception("There was no cognitoIdentityId in the API event.")

        identity["cognitoIdentityId"] = cognito_identity_id
        identity["userPoolSub"] = cognito_authentication_provider.split(':')[-1]

    return identity


def get_api_identity():
    api_identity = {}
    try:
        api_identity["API_IDENTITY_ID"] = os.environ['API_IDENTITY_ID']
        api_identity["API_USERPOOL_SUB"] = os.environ['API_USERPOOL_SUB']
    except KeyError:
        logger.error('API_IDENTITY_ID and API_USERPOOL_SUB environment variables not set correctly')
        raise Exception('API_IDENTITY_ID and API_USERPOOL_SUB environment variables not set correctly')

    return api_identity


def get_table_name():
    try:
        table_name = os.environ['TABLE_NAME']
        logger.info("TABLE_NAME environment variable value: " + table_name)
    except KeyError:
        logger.error('TABLE_NAME environment variable not set correctly')
        raise Exception('TABLE_NAME environment variable not set correctly')

    return table_name


def create_response(code, body):
    logger.info("Creating response with status code ({}) and body ({})".format(code, body))
    response = {'statusCode': code,
                'body': body,
                'headers': {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*'
                }}
    return response
