AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless resources for lists service

Globals:
    Function:
        Timeout: 3

Parameters:
  Environment:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - staging
      - dev
      - test
    ConstraintDescription: must specify prod, staging, dev or test.
  ServiceName:
    Description: Service name.
    Default: lists
    Type: String
  TableNamePrefix:
    Description: Name of dynamoDB table.
    Default: lists
    Type: String

Resources:
  CreateListFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ServiceName}-${Environment}'
      Handler: lists/create.handler
      Runtime: python3.6
      MemorySize: 512
      Timeout: 3
      Description: Creates list items in table
      Role: !GetAtt FunctionRole.Arn
      Environment:
        Variables:
          DB_NAME: !Sub '${TableNamePrefix}-${Environment}'
      # Events:
      #   UnsolvedPuzzle:
      #     Type: Api
      #     Properties:
      #       RestApiId: !Ref Api
      #       Path: /puzzle
      #       Method: GET

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ServiceName}-${Environment}-Role'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: ListsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Scan'
                  - 'dynamodb:DeleteItem'
                Resource:
                  - !Sub "arn:aws:dynamodb:$REGION:$ACC:table/${TableNamePrefix}-${Environment}"

# Outputs:
